import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { pool } from "./db.js";
import { config } from "./config.js";

const COOKIE = config.NODE_ENV === "production" ? "__Host-vansha_access_token" : "vansha_access_token";

function cookie(request: FastifyRequest) {
  const h=request.headers.cookie; if(!h) return null;
  for(const p of h.split(";")) { const [n,...v]=p.trim().split("="); if(n===COOKIE) return decodeURIComponent(v.join("=")); }
  return null;
}
function sameOrigin(request: FastifyRequest) {
  if(!["GET","HEAD","OPTIONS"].includes(request.method) && request.headers.origin && request.headers.origin!==config.CORS_ORIGIN)
    throw Object.assign(new Error("Cross-site request blocked"),{statusCode:403});
}
async function auth(app:FastifyInstance,request:FastifyRequest) {
  const t=cookie(request); if(t){sameOrigin(request);request.user=await app.jwt.verify(t);} else await request.jwtVerify();
  const p=request.user as {sub?:string;companyId?:string;email?:string;sid?:string};
  if(!p.sub||!p.companyId||!p.email||!p.sid) throw Object.assign(new Error("Authentication required"),{statusCode:401});
  const r=await pool.query("SELECT u.id,u.company_id,u.email FROM users u JOIN auth_sessions s ON s.user_id=u.id JOIN companies c ON c.id=u.company_id WHERE u.id=$1 AND u.company_id=$2 AND s.id=$3 AND u.status='active' AND c.status='active' AND s.revoked_at IS NULL AND s.expires_at>NOW()",[p.sub,p.companyId,p.sid]);
  if(r.rowCount!==1) throw Object.assign(new Error("Session is invalid or expired"),{statusCode:401});
  const roles=await pool.query("SELECT r.name FROM roles r JOIN user_roles ur ON ur.role_id=r.id WHERE ur.user_id=$1 AND r.company_id=$2",[p.sub,p.companyId]);
  await pool.query("UPDATE auth_sessions SET last_seen_at=NOW() WHERE id=$1",[p.sid]);
  return {id:String(r.rows[0].id),companyId:String(r.rows[0].company_id),email:String(r.rows[0].email),roles:roles.rows.map(x=>String(x.name))};
}
function access(u:{roles:string[]}) { if(!u.roles.some(r=>["Company Admin","Super Admin","Management","Sales/CRM"].includes(r))) throw Object.assign(new Error("CRM access required"),{statusCode:403}); }
function fail(reply:any,e:unknown,msg:string){
  const status=typeof e==="object"&&e&&"statusCode"in e&&typeof (e as any).statusCode==="number"?(e as any).statusCode:400;
  const code=(e as any)?.code==="23505"?"CONFLICT":status===403?"FORBIDDEN":"REQUEST_ERROR";
  const message=code==="CONFLICT"?"A CRM record with the same unique value already exists":status===403?(e as any).message:msg;
  return reply.code(code==="CONFLICT"?409:status).send({error:{code,message}});
}
async function hist(u:any,type:string,id:string,action:string,description:string){await pool.query("INSERT INTO crm_history(company_id,entity_type,entity_id,action,description,changed_by) VALUES($1,$2,$3,$4,$5,$6)",[u.companyId,type,id,action,description,u.id]);}
const lead=z.object({companyName:z.string().trim().min(2).max(200),contactName:z.string().trim().max(150).nullable().optional(),email:z.string().email().nullable().optional(),phone:z.string().trim().max(30).nullable().optional(),source:z.string().trim().max(80).nullable().optional(),status:z.enum(["new","contacted","qualified","proposal","won","lost"]).default("new"),priority:z.enum(["low","normal","high","urgent"]).default("normal"),requirementSummary:z.string().trim().max(2000).nullable().optional(),nextFollowUpAt:z.string().datetime().nullable().optional()});
const customer=z.object({code:z.string().trim().min(2).max(40).regex(/^[A-Za-z0-9_-]+$/),legalName:z.string().trim().min(2).max(200),tradeName:z.string().trim().max(200).nullable().optional(),gstin:z.string().trim().max(20).nullable().optional(),pan:z.string().trim().max(20).nullable().optional(),email:z.string().email().nullable().optional(),phone:z.string().trim().max(30).nullable().optional(),creditLimit:z.number().nonnegative().nullable().optional(),creditDays:z.number().int().nonnegative().max(365).nullable().optional()});
const contact=z.object({customerId:z.string().uuid(),name:z.string().trim().min(2).max(150),designation:z.string().trim().max(100).nullable().optional(),email:z.string().email().nullable().optional(),phone:z.string().trim().max(30).nullable().optional(),isPrimary:z.boolean().default(false)});
const enquiry=z.object({leadId:z.string().uuid().nullable().optional(),customerId:z.string().uuid().nullable().optional(),contactId:z.string().uuid().nullable().optional(),pickupLocation:z.string().trim().max(250).nullable().optional(),deliveryLocation:z.string().trim().max(250).nullable().optional(),productName:z.string().trim().max(150).nullable().optional(),quantity:z.number().nonnegative().nullable().optional(),quantityUnit:z.string().trim().max(30).nullable().optional(),vehicleType:z.string().trim().max(100).nullable().optional(),heatingRequired:z.boolean().default(false),temperatureRequirement:z.string().trim().max(100).nullable().optional(),hazardous:z.boolean().default(false),requirementNotes:z.string().trim().max(2000).nullable().optional()});
const followup=z.object({leadId:z.string().uuid().nullable().optional(),enquiryId:z.string().uuid().nullable().optional(),customerId:z.string().uuid().nullable().optional(),followUpAt:z.string().datetime(),channel:z.enum(["call","whatsapp","email","meeting","other"]).default("call"),subject:z.string().trim().min(2).max(200),notes:z.string().trim().max(2000).nullable().optional()}).refine(v=>v.leadId||v.enquiryId||v.customerId,{message:"A lead, enquiry or customer is required"});
const quote=z.object({enquiryId:z.string().uuid().nullable().optional(),customerId:z.string().uuid().nullable().optional(),quotationNo:z.string().trim().min(2).max(50),version:z.number().int().positive().default(1),status:z.enum(["draft","sent","accepted","rejected","expired","cancelled"]).default("draft"),validUntil:z.string().date().nullable().optional(),freightAmount:z.number().nonnegative().nullable().optional(),additionalCharges:z.number().nonnegative().default(0),detentionCharges:z.number().nonnegative().default(0),heatingCharges:z.number().nonnegative().default(0),taxAmount:z.number().nonnegative().default(0),totalAmount:z.number().nonnegative().nullable().optional(),terms:z.string().max(4000).nullable().optional()});
const negotiation=z.object({enquiryId:z.string().uuid().nullable().optional(),quotationId:z.string().uuid().nullable().optional(),customerId:z.string().uuid().nullable().optional(),channel:z.enum(["call","whatsapp","email","meeting","other"]).default("call"),summary:z.string().trim().min(2).max(4000),agreedAmount:z.number().nonnegative().nullable().optional(),nextAction:z.string().max(1000).nullable().optional(),nextActionAt:z.string().datetime().nullable().optional()});

export async function registerCrmRoutes(app:FastifyInstance){
  app.get("/api/v1/crm/summary",async(req,rep)=>{try{const u=await auth(app,req);access(u);const [l,c,e,f,q,n]=await Promise.all(["crm_leads","crm_customers","crm_enquiries","crm_followups","crm_quotations","crm_negotiations"].map(t=>pool.query("SELECT COUNT(*) FROM "+t+" WHERE company_id=$1",[u.companyId])));return {leads:Number(l.rows[0].count),customers:Number(c.rows[0].count),enquiries:Number(e.rows[0].count),pendingFollowups:Number(f.rows[0].count),quotations:Number(q.rows[0].count),negotiations:Number(n.rows[0].count)};}catch(e){return fail(rep,e,"Unable to load CRM summary")}});
  app.get("/api/v1/crm/leads",async(req,rep)=>{try{const u=await auth(app,req);access(u);const r=await pool.query("SELECT * FROM crm_leads WHERE company_id=$1 ORDER BY created_at DESC",[u.companyId]);return {leads:r.rows}}catch(e){return fail(rep,e,"Unable to load leads")}});
  app.post("/api/v1/crm/leads",async(req,rep)=>{try{const u=await auth(app,req);access(u);const v=lead.parse(req.body);const r=await pool.query("INSERT INTO crm_leads(company_id,owner_user_id,company_name,contact_name,email,phone,source,status,priority,requirement_summary,next_follow_up_at,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$2,$2) RETURNING *",[u.companyId,u.id,v.companyName,v.contactName??null,v.email??null,v.phone??null,v.source??null,v.status,v.priority,v.requirementSummary??null,v.nextFollowUpAt??null]);await hist(u,"lead",r.rows[0].id,"created","Lead created");return rep.code(201).send({lead:r.rows[0]})}catch(e){return fail(rep,e,"Lead creation failed")}});
  app.patch("/api/v1/crm/leads/:id",async(req,rep)=>{try{const u=await auth(app,req);access(u);const id=z.string().uuid().parse((req.params as any).id),v=lead.partial().parse(req.body),map:any={companyName:"company_name",contactName:"contact_name",email:"email",phone:"phone",source:"source",status:"status",priority:"priority",requirementSummary:"requirement_summary",nextFollowUpAt:"next_follow_up_at"},set:string[]=[],val:any[]=[];for(const[k,c]of Object.entries(map))if(v[k]!==undefined){val.push(v[k]);set.push(c+"=$"+val.length)}if(!set.length)return rep.code(400).send({error:{code:"NO_CHANGES",message:"No lead fields supplied"}});val.push(u.id,id,u.companyId);const r=await pool.query("UPDATE crm_leads SET "+set.join(",")+",updated_by=$"+(val.length-2)+",updated_at=NOW() WHERE id=$"+(val.length-1)+" AND company_id=$"+val.length+" RETURNING *",val);if(r.rowCount!==1)return rep.code(404).send({error:{code:"LEAD_NOT_FOUND",message:"Lead not found"}});await hist(u,"lead",id,"updated","Lead updated");return {lead:r.rows[0]}}catch(e){return fail(rep,e,"Lead update failed")}});
  app.get("/api/v1/crm/customers",async(req,rep)=>{try{const u=await auth(app,req);access(u);const r=await pool.query("SELECT * FROM crm_customers WHERE company_id=$1 ORDER BY legal_name",[u.companyId]);return {customers:r.rows}}catch(e){return fail(rep,e,"Unable to load customers")}});
  app.post("/api/v1/crm/customers",async(req,rep)=>{try{const u=await auth(app,req);access(u);const v=customer.parse(req.body);const r=await pool.query("INSERT INTO crm_customers(company_id,code,legal_name,trade_name,gstin,pan,email,phone,credit_limit,credit_days,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11) RETURNING *",[u.companyId,v.code.toUpperCase(),v.legalName,v.tradeName??null,v.gstin??null,v.pan??null,v.email??null,v.phone??null,v.creditLimit??null,v.creditDays??null,u.id]);await hist(u,"customer",r.rows[0].id,"created","Customer created");return rep.code(201).send({customer:r.rows[0]})}catch(e){return fail(rep,e,"Customer creation failed")}});
  app.get("/api/v1/crm/contacts",async(req,rep)=>{try{const u=await auth(app,req);access(u);const r=await pool.query("SELECT * FROM crm_contacts WHERE company_id=$1 ORDER BY name",[u.companyId]);return {contacts:r.rows}}catch(e){return fail(rep,e,"Unable to load contacts")}});
  app.post("/api/v1/crm/contacts",async(req,rep)=>{try{const u=await auth(app,req);access(u);const v=contact.parse(req.body);const c=await pool.query("SELECT id FROM crm_customers WHERE id=$1 AND company_id=$2",[v.customerId,u.companyId]);if(c.rowCount!==1)return rep.code(404).send({error:{code:"CUSTOMER_NOT_FOUND",message:"Customer not found"}});const r=await pool.query("INSERT INTO crm_contacts(company_id,customer_id,name,designation,email,phone,is_primary) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[u.companyId,v.customerId,v.name,v.designation??null,v.email??null,v.phone??null,v.isPrimary]);await hist(u,"contact",r.rows[0].id,"created","Contact created");return rep.code(201).send({contact:r.rows[0]})}catch(e){return fail(rep,e,"Contact creation failed")}});
  app.get("/api/v1/crm/enquiries",async(req,rep)=>{try{const u=await auth(app,req);access(u);const r=await pool.query("SELECT * FROM crm_enquiries WHERE company_id=$1 ORDER BY created_at DESC",[u.companyId]);return {enquiries:r.rows}}catch(e){return fail(rep,e,"Unable to load enquiries")}});
  app.post("/api/v1/crm/enquiries",async(req,rep)=>{try{const u=await auth(app,req);access(u);const v=enquiry.parse(req.body);const n=await pool.query("SELECT COUNT(*)+1 AS n FROM crm_enquiries WHERE company_id=$1",[u.companyId]);const no="ENQ-"+String(n.rows[0].n).padStart(5,"0");const r=await pool.query("INSERT INTO crm_enquiries(company_id,lead_id,customer_id,contact_id,enquiry_no,pickup_location,delivery_location,product_name,quantity,quantity_unit,vehicle_type,heating_required,temperature_requirement,hazardous,requirement_notes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$16) RETURNING *",[u.companyId,v.leadId??null,v.customerId??null,v.contactId??null,no,v.pickupLocation??null,v.deliveryLocation??null,v.productName??null,v.quantity??null,v.quantityUnit??null,v.vehicleType??null,v.heatingRequired,v.temperatureRequirement??null,v.hazardous,v.requirementNotes??null,u.id]);await hist(u,"enquiry",r.rows[0].id,"created","Enquiry created");return rep.code(201).send({enquiry:r.rows[0]})}catch(e){return fail(rep,e,"Enquiry creation failed")}});
  app.get("/api/v1/crm/followups",async(req,rep)=>{try{const u=await auth(app,req);access(u);const r=await pool.query("SELECT * FROM crm_followups WHERE company_id=$1 ORDER BY follow_up_at",[u.companyId]);return {followups:r.rows}}catch(e){return fail(rep,e,"Unable to load follow-ups")}});
  app.post("/api/v1/crm/followups",async(req,rep)=>{try{const u=await auth(app,req);access(u);const v=followup.parse(req.body);const r=await pool.query("INSERT INTO crm_followups(company_id,lead_id,enquiry_id,customer_id,follow_up_at,channel,subject,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",[u.companyId,v.leadId??null,v.enquiryId??null,v.customerId??null,v.followUpAt,v.channel,v.subject,v.notes??null,u.id]);await hist(u,"followup",r.rows[0].id,"created","Follow-up created");return rep.code(201).send({followup:r.rows[0]})}catch(e){return fail(rep,e,"Follow-up creation failed")}});
  app.get("/api/v1/crm/quotations",async(req,rep)=>{try{const u=await auth(app,req);access(u);const r=await pool.query("SELECT * FROM crm_quotations WHERE company_id=$1 ORDER BY created_at DESC",[u.companyId]);return {quotations:r.rows}}catch(e){return fail(rep,e,"Unable to load quotations")}});
  app.post("/api/v1/crm/quotations",async(req,rep)=>{try{const u=await auth(app,req);access(u);const v=quote.parse(req.body);const r=await pool.query("INSERT INTO crm_quotations(company_id,enquiry_id,customer_id,quotation_no,version,status,valid_until,freight_amount,additional_charges,detention_charges,heating_charges,tax_amount,total_amount,terms,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$15) RETURNING *",[u.companyId,v.enquiryId??null,v.customerId??null,v.quotationNo.toUpperCase(),v.version,v.status,v.validUntil??null,v.freightAmount??null,v.additionalCharges,v.detentionCharges,v.heatingCharges,v.taxAmount,v.totalAmount??null,v.terms??null,u.id]);await hist(u,"quotation",r.rows[0].id,"created","Quotation created");return rep.code(201).send({quotation:r.rows[0]})}catch(e){return fail(rep,e,"Quotation creation failed")}});
  app.get("/api/v1/crm/negotiations",async(req,rep)=>{try{const u=await auth(app,req);access(u);const r=await pool.query("SELECT * FROM crm_negotiations WHERE company_id=$1 ORDER BY discussion_at DESC",[u.companyId]);return {negotiations:r.rows}}catch(e){return fail(rep,e,"Unable to load negotiations")}});
  app.post("/api/v1/crm/negotiations",async(req,rep)=>{try{const u=await auth(app,req);access(u);const v=negotiation.parse(req.body);const r=await pool.query("INSERT INTO crm_negotiations(company_id,enquiry_id,quotation_id,customer_id,discussed_by,channel,summary,agreed_amount,next_action,next_action_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *",[u.companyId,v.enquiryId??null,v.quotationId??null,v.customerId??null,u.id,v.channel,v.summary,v.agreedAmount??null,v.nextAction??null,v.nextActionAt??null]);await hist(u,"negotiation",r.rows[0].id,"created","Negotiation created");return rep.code(201).send({negotiation:r.rows[0]})}});
  app.get("/api/v1/crm/history/:entityType/:entityId",async(req,rep)=>{try{const u=await auth(app,req);access(u);const t=z.enum(["lead","enquiry","customer","contact","followup","quotation","negotiation"]).parse((req.params as any).entityType),id=z.string().uuid().parse((req.params as any).entityId);const r=await pool.query("SELECT * FROM crm_history WHERE company_id=$1 AND entity_type=$2 AND entity_id=$3 ORDER BY created_at DESC",[u.companyId,t,id]);return {history:r.rows}}catch(e){return fail(rep,e,"Unable to load CRM history")}});
}
